apiVersion: v1
kind: Service
metadata:
  name: norah
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: norah
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: norah
spec:
  replicas: 2
  selector:
    matchLabels:
      app: norah
  template:
    metadata:
      labels:
        app: norah
    spec:
      containers:
      - name: norah
        image: 147005956006.dkr.ecr.us-west-2.amazonaws.com/norah:latest
        ports:
        - containerPort: 8080